# Generated by Django 4.1.2 on 2024-05-01 14:00

from django.db import migrations
import kategoriler.models


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_adi',
            name='site_url_ayari',
            field=kategoriler.models.kategory_link_ayari(max_length=100, null='True'),
            preserve_default='True',
        ),
    ]
