# Generated by Django 4.1.2 on 2024-05-01 15:43

from django.db import migrations, models
import kategoriler.models


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0002_site_adi_site_url_ayari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_adi',
            name='site_adi_genel',
            field=models.CharField(max_length=200, verbose_name='İşletme Adı'),
        ),
        migrations.AlterField(
            model_name='site_adi',
            name='site_url_ayari',
            field=kategoriler.models.kategory_link_ayari(default=1, max_length=100, verbose_name='İşletme Adı'),
            preserve_default=False,
        ),
    ]
