# Generated by Django 4.1.2 on 2024-05-02 16:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0003_alter_site_adi_site_adi_genel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hakkimizda',
            name='hakkimda',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='numara',
            name='sirket_numarasi',
            field=models.CharField(max_length=11, verbose_name='İşletme Numarası (0555555555)'),
        ),
        migrations.AlterField(
            model_name='sosyalmedyainsgr',
            name='link',
            field=models.CharField(max_length=400, verbose_name='İnstagram Adres Linki'),
        ),
    ]
