# Generated by Django 4.1.2 on 2024-05-02 16:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0004_alter_hakkimizda_hakkimda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hakkimizda',
            name='hakkimda',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
