# Generated by Django 4.1.2 on 2024-05-03 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kategoriler', '0005_alter_hakkimizda_hakkimda'),
    ]

    operations = [
        migrations.CreateModel(
            name='bolgeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolge_isimi', models.CharField(max_length=200, verbose_name='Bölge Adı')),
                ('kategori_kime_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='masalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masa_isimi', models.CharField(max_length=200, verbose_name='Masa Adı')),
                ('bolge_isimi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kategoriler.bolgeler', verbose_name='Bölge ')),
                ('kategori_kime_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
