# Generated by Django 4.1.2 on 2024-05-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0006_bolgeler_masalar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolgeler',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False, verbose_name='Silinme Bilgisi'),
        ),
        migrations.AddField(
            model_name='masalar',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False, verbose_name='Silinme Bilgisi'),
        ),
    ]
