# Generated by Django 4.1.2 on 2024-05-03 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kategoriler', '0007_bolgeler_silinme_bilgisi_masalar_silinme_bilgisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_isimi', models.CharField(max_length=200, verbose_name='Menü Adı')),
                ('silinme_bilgisi', models.BooleanField(default=False, verbose_name='Silinme Bilgisi')),
                ('kategori_kime_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bolgeler',
            name='bolge_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kategoriler.menu', verbose_name='Bölge '),
        ),
    ]
