# Generated by Django 4.1.2 on 2024-05-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0008_menu_bolgeler_bolge_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='masalar',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='qr/', verbose_name='Masa Qrları'),
        ),
        migrations.AlterField(
            model_name='bolgeler',
            name='bolge_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kategoriler.menu', verbose_name='Menü '),
        ),
    ]
