# Generated by Django 4.1.2 on 2024-05-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0009_masalar_image_alter_bolgeler_bolge_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masalar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='qr/', verbose_name='Masa Qrları'),
        ),
    ]
