# Generated by Django 4.1.2 on 2024-05-04 12:57

from django.db import migrations, models
import django.db.models.deletion
import kategoriler.models


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0010_alter_masalar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriler',
            name='Durum',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default='Evet', max_length=10, verbose_name='Menüde Göster'),
        ),
        migrations.AlterField(
            model_name='kategoriler',
            name='isim',
            field=models.CharField(max_length=150, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='kategoriler',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='kategoriler.kategoriler', verbose_name='Üst KAtegorisi Var Mı ? '),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='Durum',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default='Evet', max_length=10, verbose_name='Menüde Göster'),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kategoriler.kategoriler', verbose_name='Kategorisi'),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fiyatı'),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='isim',
            field=models.CharField(max_length=150, verbose_name='İsmi'),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='link',
            field=kategoriler.models.kategory_link_ayari(max_length=100, null='True', verbose_name='Tanıtım Açıklaması'),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='siralama',
            field=models.BigIntegerField(null=True, verbose_name='Sıralaması'),
        ),
    ]
