# Generated by Django 4.1.2 on 2024-05-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0011_kategoriler_durum_alter_kategoriler_isim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriler',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False, verbose_name='Silinme Bilgisi'),
        ),
        migrations.AddField(
            model_name='urunler',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False, verbose_name='Silinme Bilgisi'),
        ),
    ]
