# Generated by Django 4.1.2 on 2024-05-04 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kategoriler', '0012_kategoriler_silinme_bilgisi_urunler_silinme_bilgisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoriler',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='kategoriler.kategoriler', verbose_name='Üst Kategorisi Var Mı ? '),
        ),
        migrations.CreateModel(
            name='birimler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim_isimi', models.CharField(max_length=200, verbose_name='Birim Adı')),
                ('silinme_bilgisi', models.BooleanField(default=False, verbose_name='Silinme Bilgisi')),
                ('kategori_kime_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
