# Generated by Django 4.1.2 on 2024-05-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0013_alter_kategoriler_parent_birimler'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='birim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kategoriler.birimler', verbose_name='Birimi'),
            preserve_default=False,
        ),
    ]
