# Generated by Django 4.1.2 on 2024-05-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0014_urunler_birim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='birim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kategoriler.birimler', verbose_name='Birimi'),
        ),
    ]
