# Generated by Django 4.1.2 on 2024-05-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0015_alter_urunler_birim'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='adet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Adet'),
        ),
    ]
