# Generated by Django 4.1.2 on 2024-05-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriler', '0016_urunler_adet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='keywords',
            field=models.CharField(max_length=255, null='True', verbose_name='Tanıtım Açıklaması'),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='resimi',
            field=models.ImageField(upload_to='images/', verbose_name='Ürün Resmi'),
        ),
    ]
